version: '3.8'
services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: ./backend
    environment:
      DB_HOST: db
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
volumes:
  db-data:


